### PR TITLE
Replaced deprecated `ancestorStateOfType` method

### PR DESCRIPTION
**Pull request by OscarFKE**
Replaced deprecated `ancestorStateOfType` call with call to `findAncestorStateOfType`

### CODE REVIEW

**Review by Theunodb — APPROVED** [review]
Looks good

**Comment by lindanimasinga** [comment]
When should we expect this merged and released?

**Comment by jerryrt** [comment]
Flutter 2.0 is out there, and this issue is a blocking issue in projects that depends on this package during the upgrade. Can the merge be prioritized and released?

**Comment by poolapal** [comment]
@OscarFKE  Try to merge this branch and publish ASAP. this issue was breaking my project.

**Comment by MadhanAD** [comment]
Try to merge this branch and publish ASAP. this issue was breaking my project.

**Review by KevMorelli — APPROVED** [review]

**Pull request merged**
