### PR TITLE
Update RxDart

### PR DESCRIPTION
**Pull request by billsakkas**
I updated RxDart to version 0.23.1 and worked fine when I tried it.

### CODE REVIEW

**Comment by rahuldange09** [comment]
If possible can you update other packages also to latest version?

**Comment by billsakkas** [comment]
Sure, I will do it after work.

**Comment by rahuldange09** [comment]
Hi, Can you tell me how can i use your commit in pubspec.yml directly?

**Comment by billsakkas** [comment]
Sorry for the late response. In order to use my commit, you have to add the text below to your dependencies in your pubspec.yml

```
dependencies:
  flutter_google_places:
    git: git://github.com/billsakkas/flutter_google_places.git
```

Also keep in mind that this is a fork of the original flutter_google_places package and I might remove it in the future. You should probably make a fork of it and then make any changes you desire.

**Comment by rahuldange09** [comment]
> Sorry for the late response. In order to use my commit, you have to add the text below to your dependencies in your pubspec.yml
> 
> ```
> dependencies:
>   flutter_google_places:
>     git: git://github.com/billsakkas/flutter_google_places.git
> ```
> 
> Also keep in mind that this is a fork of the original flutter_google_places package and I might remove it in the future. You should probably make a fork of it and then make any changes you desire.

Sure,
thanks for help buddy

**Comment by ayushin** [comment]
Is this project still maintained? I see a few useful PRs for a while and no merging?

**Comment by KevMorelli** [comment]
@ayushin Sorry about that, there were a few organizational and maintenance changes. We will start to put this project back on track.

**Pull request merged**
